# Generated by Django 3.2 on 2023-03-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='empty', max_length=254, unique=True, verbose_name='Token'),
        ),
        migrations.DeleteModel(
            name='JWTToken',
        ),
    ]
