# Generated by Django 3.2 on 2023-03-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230327_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='empty', max_length=254, unique=True, verbose_name='Token'),
        ),
    ]
