# Generated by Django 3.2 on 2023-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230316_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Confirmation_code'),
        ),
    ]
